version: 1.0.{build}
image: Visual Studio 2017
before_build:
- ps: dotnet restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 1TRtLMdrz0Uw+6VWQBSUG49Wf6zlHRzMk0FfIRDdw9+4ciMeAkDKcswpI8aAMbxc
  on:
    branch: master