version: 1.0.{build}
image: Visual Studio 2017
before_build:
- ps: dotnet restore
configuration:
  - Debug
  - Release
build:
  publish_nuget: true
  verbosity: minimal
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(appveyor_build_version)
deploy:
- provider: NuGet
  api_key:
    secure: E4heJugG3N/H1/Jxs3NVKi/h92oz7FpEH0hfVWSubjC9fWdOnwKRErVQ4HHL3wwM
  on:
    branch: master
    configuration: Release
